name: Release
on: [workflow_dispatch]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Release
        if: github.ref == 'refs/heads/master'
        run: yarn release && git push origin master --follow-tags && yarn publish