name: Release
on: [workflow_dispatch]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'
        run: git config --global user.email "andrebnassis@gmail.com" && git config --global user.name "andrebnassis" && yarn release --skip.bump --skip.tag  && git push --follow-tags

      - name: Publish
        env:
          # Use a token to publish to NPM. See below for how to set it up
          YARN_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}" && yarn publish --non-interactive
      